# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75441841d55634387cea99380455cd8438aa4f6276f44763377177bedaeacaafd6a849cd17f2ba99ed9aa1e2a75f5e19d861281d14cc6f0dfa38765a21373b84

test:
  secret_key_base: b7870c3ac86af1d197d100ed2399915362736b8c10a73fb3ad95641704fc965918ed3ed737c89b66bf3885756e1aa65f0c776f3d96a2292350517da6c45abf20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
